/**
 * Auto-generated typed API client for Bunbox
 * Do not edit this file manually
 */

async function request<T>(method: string, path: string, opts?: any): Promise<T> {
  let url = path;
  if (opts?.params) {
    for (const [k, v] of Object.entries(opts.params)) url = url.replace(`[${k}]`, String(v));
  }
  if (opts?.query) {
    const p = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.query)) p.append(k, String(v));
    url += `?${p}`;
  }
  if (url.startsWith("/") && typeof window === "undefined") {
    url = `http://${process.env.BUNBOX_HOSTNAME || "localhost" }:${process.env.BUNBOX_PORT || "3000"}${url}`;
  }
  const res = await fetch(url, {
    method,
    headers: { "Content-Type": "application/json", ...opts?.headers },
    body: opts?.body && method !== "GET" ? JSON.stringify(opts.body) : undefined,
  });
  if (!res.ok) throw new Error(await res.text());
  return res.json();
}

export const api = {
};