/**
 * Auto-generated entry point for Bunbox client
 * Do not edit this file manually
 */

import { initBunbox } from "/Users/anthonydemattos/bunbox/packages/bunbox/src/client/hydrate.tsx";
import { routes, layouts, ssrPages } from "./routes";

// Initialize the app
initBunbox(routes, layouts, ssrPages).catch((error) => {
  console.error("Failed to initialize Bunbox app:", error);
});
